# Numpy array使用的区别

In [1]:
print([3,4,5] + [1])
print((3,2,4) + (1,))
print((3,2,4) + (1))

[3, 4, 5, 1]
(3, 2, 4, 1)


TypeError: can only concatenate tuple (not "int") to tuple

In [2]:
import numpy as np
c = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,3,1],[3,2,4,1]]])
print(c.shape)
print(c[1:2])    # 获得同样维度的值
print(c[1:2][0])

(2, 2, 4)
[[[5 6 3 1]
  [3 2 4 1]]]
[[5 6 3 1]
 [3 2 4 1]]


In [3]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c[1:2])
print(c[1:2][0])
print(c[1])

[[5 6 7 8]]
[5 6 7 8]
[5 6 7 8]


** 浅拷贝与深拷贝 **

In [4]:
c = np.array([[1,2,3,4],[5,6,7,8]])
a = c[1]
a[:] = 0
print(c)    # 浅拷贝，仍指向/使用原来的内存

[[1 2 3 4]
 [0 0 0 0]]


In [5]:
l = list(c)    # 不过list和ndarray不同, 以例保存ndarray
l[1] = [1,3,4,5]
print(l)
print(c) # 深拷贝，不共享空间

[array([1, 2, 3, 4]), [1, 3, 4, 5]]
[[1 2 3 4]
 [0 0 0 0]]


In [6]:
b = c.copy()
c[1,3] = 4
print(b)    # 深拷贝
print(c)

[[1 2 3 4]
 [0 0 0 0]]
[[1 2 3 4]
 [0 0 0 4]]


** 布尔索引与列表索引 **

In [7]:
print(c > 1)
c[c>1]

[[False  True  True  True]
 [False False False  True]]


array([2, 3, 4, 4])

In [8]:
x=np.arange(10)  
index=[1,2,3,4,5]  
arr_index=np.array(index)  
print(x)
print(x[index])  # list索引  
print(x[arr_index])  # array索引  

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[1 2 3 4 5]


** list和np.array的区别 **

In [9]:
import numpy as np
a=np.arange(10)  
lista=list(a)  
print(a*2)  
print(lista*2) 

[ 0  2  4  6  8 10 12 14 16 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


** array广播 **

In [13]:
a = np.arange(0, 60, 10).reshape(-1, 1) # 横向broadcast
b = np.arange(0, 5)  # 纵向broadcast
print(a)  
print(b)
b.shape

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[0 1 2 3 4]


(5,)

In [11]:
print(np.add(a,b))
print(a + b)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]


In [12]:
import numpy as np
a = np.array([[1,2],[4,5]])
print(np.sum(a, axis=0))    # 沿axis=0轴求和

[5 7]
