# Compatibility

In [1]:
#! /usr/bin/env python
# -*- coding: utf-8 -*-

In [2]:
from __future__ import unicode_literals

In [3]:
print '\'xxx\' is unicode?', isinstance('xxx', unicode)

'xxx' is unicode? True


In [4]:
format(0.025,'.2e')

u'2.50e-02'

# IO Samples

In [5]:
input = raw_input('Who are you? ')

Who are you? Michael


In [6]:
print r"""line1\n
line2"""

line1\n
line2


In [7]:
print "{0} is {1}".format('He',"Michael")

He is Michael


# Encoding and decoding of String

In [8]:
print ord('A'),chr(65)

65 A


In [9]:
print u'4e3d'

4e3d


In [10]:
u'中'

u'\u4e2d'

In [11]:
'中'

u'\u4e2d'

In [12]:
print u'\u4e2d'

中


## 编码成UTF-8编码

In [13]:
u'ABC'.encode('utf-8')

'ABC'

In [14]:
u'中'.encode('utf-8')

'\xe4\xb8\xad'

In [15]:
len(u'中国')

2

In [16]:
len(u'中国'.encode('utf-8'))

6

## 解码成Unicode编码(解码至内存为Unicode)

In [18]:
b'\xe4\xb8\xad'.decode('utf-8')

u'\u4e2d'

In [19]:
'abc'.decode('utf-8')

u'abc'

# Python 除法向负无穷取整（C语言向0取整）

In [20]:
-10/3

-4

## 取余 a%n = a - n*[a/n]

In [21]:
-10%3 == -10 - 3*(-10/3)

True

## Tuple

In [22]:
t = (1)
t

1

In [23]:
t = (1,)
t

(1,)

In [24]:
print id(t)

140460940672336


In [25]:
x=""
if x:
    print "True"

In [26]:
dict = {"M":10,"N":20,"E":50}
'E' in dict

True

## Dict 的key必须是不可变对象

In [27]:
dict[(1,2,3)] = 2

In [28]:
dict[(1,[2,3])] = 2

TypeError: unhashable type: 'list'

In [29]:
help(cmp)

Help on built-in function cmp in module __builtin__:

cmp(...)
    cmp(x, y) -> integer
    
    Return negative if x<y, zero if x==y, positive if x>y.



In [30]:
help(int)

Help on class int in module __builtin__:

class int(object)
 |  int(x=0) -> int or long
 |  int(x, base=10) -> int or long
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is floating point, the conversion truncates towards zero.
 |  If x is outside the integer range, the function returns a long instead.
 |  
 |  If x is not a number or if base is given, then x must be a string or
 |  Unicode object representing an integer literal in the given base.  The
 |  literal can be preceded by '+' or '-' and be surrounded by whitespace.
 |  The base defaults to 10.  Valid bases are 0 and 2-36.  Base 0 means to
 |  interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(...)
 |      x.__abs__() <==> abs(x)
 |  
 |  __add__(...)
 |      x.__add__(y) <==> x+y
 |  
 |  __and__(...)
 |      x.__and__(y) <==> x&y
 |  
 |  __cmp__(...)
 |      x.__cmp__(y) <==> cmp(x,

In [31]:
int(12.6)

12

In [32]:
a = abs # alias
a(-1)

1

# 函数定义

## Pass语句占位

In [33]:
def nop():
    pass
nop()

## 参数类型检查

In [34]:
def my_abs(x):
    if not isinstance(x,(int, float)):
        raise TypeError('bad operand type for my_abs().')
    if x >= 0:
        return x
    else:
        return -x

In [35]:
my_abs(1,2) # 参数个数检查python解释器自动检查

TypeError: my_abs() takes exactly 1 argument (2 given)

In [36]:
def funt():
    return 2,1 # 返回多参数即为返回tuple

In [37]:
funt()

(2, 1)

In [38]:
a,b = (3,1)

In [39]:
print a,b
print a
print b
a,b

3 1
3
1


(3, 1)

In [40]:
a = (3,1,2)
a

(3, 1, 2)

In [41]:
a,b = (3,1,2)

ValueError: too many values to unpack

# 函数参数

## 默认参数

In [42]:
def power(x, n=2):
    s = 1
    while n > 0:
        n = n - 1
        s = s * x
    return s

** 默认参数的坑（默认参数必须指向不可变对象）**

In [43]:
def add_end(L=[]):
    L.append('END')
    return L
# L -> []

In [44]:
add_end()

[u'END']

In [45]:
add_end()
# 默认参数也是一个变量，函数定义时默认参数已经初始化为[]（的地址）

[u'END', u'END']

In [46]:
def add_end(L=None):
    if L is None:
        L = []
    L.append('END')
    return L
# L -> None

In [47]:
add_end()

[u'END']

In [48]:
add_end() # 由于对象不变，多任务环境下同时读取对象不需要加锁

[u'END']

## 可变参数

In [49]:
def calc(numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum
calc([1, 2, 3]) # 参数必须组装成list或tuple

14

In [50]:
def calc(*numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum
calc(1, 2, 3) # 参数调用简化

14

In [51]:
nums = [1, 2, 3]
calc(*nums) # 把list转可变参数

14

## 关键字参数

In [52]:
def person(name, age, **kw):
    print 'name:', name, 'age:', age, 'other:', kw
person('Michael', 30)
person('Adam', 45, gender='M', job='Engineer')

name: Michael age: 30 other: {}
name: Adam age: 45 other: {'gender': u'M', 'job': u'Engineer'}


In [53]:
kw = {'city': 'Beijing', 'job': 'Engineer'}
person('Jack', 24, city=kw['city'], job=kw['job'])
person('Jack', 24, **kw) # 把dict转换成关键字参数

name: Jack age: 24 other: {'city': u'Beijing', 'job': u'Engineer'}
name: Jack age: 24 other: {u'city': u'Beijing', u'job': u'Engineer'}


## 参数组合

** 参数定义的顺序必须是：必选参数、默认参数、可变参数和关键字参数。**

In [54]:
def func(a, b, c=0, *args, **kw):
    print 'a =', a, 'b =', b, 'c =', c, 'args =', args, 'kw =', kw

In [55]:
func(1, 2)
func(1, 2, 3)
func(1, 2, c=3)
func(1, 2, 3, 'a', 'b')
func(1, 2, 3, 'a', 'b', x=99)

a = 1 b = 2 c = 0 args = () kw = {}
a = 1 b = 2 c = 3 args = () kw = {}
a = 1 b = 2 c = 3 args = () kw = {}
a = 1 b = 2 c = 3 args = (u'a', u'b') kw = {}
a = 1 b = 2 c = 3 args = (u'a', u'b') kw = {'x': 99}


In [56]:
args = (1, 2, 3, 4)
kw = {'x': 99}
func(*args, **kw)

a = 1 b = 2 c = 3 args = (4,) kw = {u'x': 99}


In [57]:
args = (1, 2)
func(*args)

a = 1 b = 2 c = 0 args = () kw = {}


In [58]:
args = (1, 2)
func(args)

TypeError: func() takes at least 2 arguments (1 given)

In [59]:
args = 3
func(*args)

TypeError: func() argument after * must be an iterable, not int

# 尾递归（Python2.7不支持尾递归优化递归函数）

In [60]:
def fact(n):
    return fact_iter(n,1)

def fact_iter(num, product):
    if num == 1:
        return product
    return fact_iter(num - 1, num * product)

In [61]:
fact(1000)

RuntimeError: maximum recursion depth exceeded

**-------**

# Python 高级特性

## Slice切片操作符

In [64]:
L = range(100) # 0-99

In [65]:
print L[0:10]
print L[:10]
print L[-10:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


** 前10个数，每两个取一个：**

In [66]:
L[:10:2]

[0, 2, 4, 6, 8]

** 所有数，每5个取一个：**

In [67]:
L[::5]

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [68]:
(0,1,2,3,4)[:3]

(0, 1, 2)

In [69]:
'ABCDEFG'[:3]

u'ABC'

## 迭代
** for ... in 作用于可迭代对象,如字符串，列表等 **

In [70]:
dict = {'a':1, 'b':2, 'c':3}
for key in dict:
    print key,  # 默认迭代key
for value in dict.itervalues():
    print value
for k, v in dict.iteritems():
    print k,v,

a c b 1
3
2
a 1 c 3 b 2


** 判断对象是否为可迭代对象 ** 

In [71]:
from collections import Iterable
isinstance('abc', Iterable)

True

** 下标循环，同时迭代索引和元素 **

In [72]:
for i, value in enumerate(['A', 'B', 'C']):
    print i, value # enumerate 将 list 变成索引-元素对

0 A
1 B
2 C


In [73]:
for x, y in [(1, 1), (2, 4), (3, 9)]:
    print x, y

1 1
2 4
3 9


## 列表生成式

In [74]:
 [x * x for x in range(1, 11) if x % 2 == 0]

[4, 16, 36, 64, 100]

In [75]:
[m + n for m in 'ABC' for n in 'XYZ']

[u'AX', u'AY', u'AZ', u'BX', u'BY', u'BZ', u'CX', u'CY', u'CZ']

In [76]:
{k:v for k, v in dict.iteritems()}

{u'a': 1, u'b': 2, u'c': 3}

## 生成器

In [77]:
tuple([x * x for x in range(1, 11)]) # tuple

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [78]:
set([x * x for x in range(1, 11)]) # set

{1, 4, 9, 16, 25, 36, 49, 64, 81, 100}

In [79]:
(x * x for x in range(1, 11)) # 生成器，用于边循环边计算

<generator object <genexpr> at 0x7fbfa3e6f8c0>

In [80]:
g = (x * x for x in range(1, 11))

In [81]:
g.next()

1

generator保存的是算法，每次调用next()，就计算出下一个元素的值，直到计算到最后一个元素，没有更多的元素时，抛出StopIteration的错误。

** 生成器也是可迭代对象 **

In [82]:
g = (x * x for x in range(1, 11))
for n in g:
    print n

1
4
9
16
25
36
49
64
81
100


## yield 定义函数式生成器

In [83]:
def fib(max): # 斐波拉契数列
    n, a, b = 0, 0, 1
    while n < max:
        print b
        a, b = b, a + b  # tuple 赋值
        n = n + 1

In [84]:
fib(5)

1
1
2
3
5


In [85]:
def fib(max): # 斐波拉契数列
    n, a, b = 0, 0, 1
    while n < max:
        yield b # yield 定义生成器
        a, b = b, a + b  # tuple 赋值
        n = n + 1

In [86]:
g = fib(5) # 有参数5定义的生成器

变成generator的函数，在每次调用next()的时候执行，遇到yield语句返回，再次执行时 **从上次返回的yield语句处** 继续执行

In [87]:
g.next()

1

In [88]:
for n in fib(6):
    print n

1
1
2
3
5
8


**---**

# 函数式编程

## 高阶函数

既然变量可以指向函数，函数的参数能接收变量，那么一个函数就可以接收另一个函数作为参数，这种函数就称之为高阶函数。

In [95]:
def add(x, y, f):
    return f(x) + f(y)
add(-5, 6, abs)

11

In [96]:
abs

<function abs>

## Map/Reduce

In [97]:
def f(x):
    return x * x
map(f, [1, 2, 3, 4, 5, 6, 7, 8, 9])

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [99]:
map(str, [1, 2, 3, 4, 5, 6, 7, 8, 9])

['1', '2', '3', '4', '5', '6', '7', '8', '9']

** reduce(f, [x1, x2, x3, x4]) = f(f(f(x1, x2), x3), x4) **

In [100]:
def add(x, y):
    return x + y
reduce(add, [1, 3, 5, 7, 9])

25

In [101]:
def fn(x, y):
    return x * 10 + y
reduce(fn, [1, 3, 5, 7, 9])

13579

In [104]:
def str2int(s):
    def fn(x, y):
        return x * 10 + y
    def char2num(s):
        return {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}[s]
    return reduce(fn, map(char2num, s))
str2int('13579')

13579

In [107]:
def char2num(s):
    return {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}[s]

def str2int(s):
    return reduce(lambda x,y: x*10+y, map(char2num, s))
str2int('13579')

13579

## Filter

In [109]:
filter(lambda x: x % 2 == 1,range(10))

[1, 3, 5, 7, 9]

In [115]:
if "":
    print "Hello"

In [148]:
def not_empty(s):
    return s and s.strip() # 删除空字符串
# and 为逻辑运算符，s为空字符串，不进行and后的运算
filter(not_empty, ['A', '', 'B', None, 'C', '  '])

[u'A', u'B', u'C']

In [151]:
not_empty("  ")

u''

In [149]:
not_empty("   A ")

u'A'

In [153]:
"" and "B"

u''

In [152]:
" " and "B"

u'B'

#### and为“短路与”, or为“短路或”

In [133]:
a = 1
b = 2
a - 1 and b + 1

0

In [139]:
a = 1
b = 2
a + 1 and b + 1

3

In [141]:
a = 1
b = 2
a - 1 or b + 1

3

In [146]:
a = 1
b = 2
a + 1 or b + 1

2

在Python中，None、任何数值类型中的0、空字符串“”、空元组()、空列表[]、空字典{}都被当作False，还有自定义类型，如果实现了 　__ nonzero __ ()　或　__ len __ () 方法且方法返回 0 或False，则其实例也被当作False，其他对象均为True。

## Sorted

In [154]:
sorted([36, 5, 12, 9, 21])

[5, 9, 12, 21, 36]

In [155]:
def reversed_cmp(x, y):
    if x > y:
        return -1
    if x < y:
        return 1
    return 0
sorted([36, 5, 12, 9, 21], reversed_cmp) # 默认升序，返回1排后面

[36, 21, 12, 9, 5]

In [156]:
sorted(['bob', 'about', 'Zoo', 'Credit']) # 'Z' > 'a'

[u'Credit', u'Zoo', u'about', u'bob']

In [157]:
def cmp_ignore_case(s1, s2):
    u1 = s1.upper()
    u2 = s2.upper()
    if u1 < u2:
        return -1
    if u1 > u2:
        return 1
    return 0
sorted(['bob', 'about', 'Zoo', 'Credit'], cmp_ignore_case)


[u'about', u'bob', u'Credit', u'Zoo']

In [170]:
sorted([36, 5, 12, 9, 21], lambda x,y: -cmp(x,y))

[36, 21, 12, 9, 5]

In [1]:
sorted([36, 5, 12, 9, 21], lambda x,y: cmp(x,y), reverse=True)

[36, 21, 12, 9, 5]

In [7]:
import operator
d = {'Michael':20, 'Danie':19, 'Mary': 23}
sorted(d, key=operator.itemgetter(1)) # 默认以dict.keys()为list进行排序 key='a' 'a' 'i'

['Mary', 'Danie', 'Michael']

In [8]:
sorted(d.iteritems(), key=operator.itemgetter(1)) # sorted 接受可迭代对象

[('Danie', 19), ('Michael', 20), ('Mary', 23)]

### Numpy array使用的区别

In [40]:
print [3,4,5] + [1]
print (3,2,4) + (1,)
print (3,2,4) + (1)

[3, 4, 5, 1]
(3, 2, 4, 1)


TypeError: can only concatenate tuple (not "int") to tuple

In [6]:
import numpy as np
c = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,3,1],[3,2,4,1]]])
print c[1:2]
print c[1:2][0]

[[[5 6 3 1]
  [3 2 4 1]]]
[[5 6 3 1]
 [3 2 4 1]]


In [8]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print c[1:2]
print c[1:2][0]
print c[1]

[[5 6 7 8]]
[5 6 7 8]
[5 6 7 8]


** 浅拷贝与深拷贝 **

In [10]:
c = np.array([[1,2,3,4],[5,6,7,8]])
a = c[1]
a[:] = 0
print c # 浅拷贝，仍指向/使用原来的内存

[[1 2 3 4]
 [0 0 0 0]]


In [14]:
l = list(c)
l[1] = [1,3,4,5]
print l
print c # 深拷贝，不共享空间

[array([1, 2, 3, 4]), [1, 3, 4, 5]]
[[1 2 3 4]
 [0 0 0 0]]


In [32]:
b = c.copy()
c[1,3] = 4
print b
print c

[[1 2 3 4]
 [0 0 0 0]]
[[1 2 3 4]
 [0 0 0 4]]


** 布尔索引与列表索引 **

In [18]:
print c >1
c[c>1]

[[False  True  True  True]
 [False False False False]]


array([2, 3, 4])

In [19]:
x=np.arange(10)  
index=[1,2,3,4,5]  
arr_index=np.array(index)  
print x  
print x[index]  # list索引  
print x[arr_index]  # array索引  

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[1 2 3 4 5]


** list和np.array的区别 **

In [2]:
import numpy as np
a=np.arange(10)  
lista=list(a)  
print a*2  
print lista*2  

[ 0  1  4  9 16 25 36 49 64 81]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


** array广播 **

In [23]:
a = np.arange(0, 60, 10).reshape(-1, 1) # 横向broadcast
b = np.arange(0, 5)  # 纵向broadcast
print a  
print b  

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[0 1 2 3 4]


In [26]:
print np.add(a,b)
print a + b

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]


In [2]:
import numpy as np
a = np.array([[1,2],[4,5]])
print np.sum(a, axis=0)